ENG-6593: Introduce support for stream event cursors
fauna/fauna-go pull request #168
Opened 2024-08-21 14:56 UTC by erickpintor

### Description

Provide support for the new per-event stream cursor.

### Motivation and context

There's an edge case where resuming a stream from a txn time with lots of documents written could result in event loss. This approach fixes that edge case.

### How was the change tested?

Unit tests included.

### Screenshots (if appropriate):

NA

### Change types

* - [X] Bug fix (non-breaking change that fixes an issue)
* - [X] New feature (non-breaking change that adds functionality)
* - [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

* - [X] My code follows the code style of this project.
* - [X] My change requires a change to Fauna documentation.
* - [X] My change requires a change to the README, and I have updated it accordingly.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-21 15:25 UTC, jrodewig approved these changes
Narrow 👍 . README looks good aside from a few nits.

2024-08-21 15:25 UTC, jrodewig commented on README.md
> +timestamp.
```suggestion
function. Use `fauna.StartTime` to restart a stream at a specific
timestamp:
```

2024-08-21 15:25 UTC, jrodewig commented on README.md
> +| `fauna.EventCursor`  | Resumes the stream after the given event cursor. Accepts an `string` with the cursor retrieved from a `fauna.Event`. |
```suggestion
| `fauna.EventCursor`  | Resumes the stream after the given event cursor. Accepts a `string` with the cursor retrieved from a `fauna.Event`. |
```

2024-08-21 15:25 UTC, jrodewig commented on README.md
> +disconnect.
```suggestion
Use `fauna.EventCursor` to resume a stream after a disconnect:

2024-08-23 08:32 UTC, pnwpedro requested changes
Only non-material feedback

2024-08-23 08:32 UTC, pnwpedro commented on README.md
> +| `fauna.EventCursor`  | Resumes the stream after the given event cursor. Accepts a `string` with the cursor retrieved from a `fauna.Event`. |
```suggestion
| `fauna.EventCursor`  | Resumes the stream after the given event cursor. Accepts a `string` representation of the cursor retrieved from a `fauna.Event`. |
```

2024-08-23 08:32 UTC, pnwpedro commented on config.go
> +// Usefull when resuming a stream after a failure.
```suggestion
// Useful when resuming a stream after a failure.
```

2024-08-23 08:32 UTC, pnwpedro commented on config.go
> +// Usefull when resuming a stream at a given point in time.
```suggestion
// Useful when resuming a stream at a given point in time.
```

2024-08-23 15:21 UTC, erickpintor commented
I've addressed all feedback. This should be ready for another pass.

2024-08-23 18:12 UTC, merged